package thainum

import "testing"

// Expected Thai readings are taken from the Dart source of truth
// (thainum.dart lib/src/percent.dart and test/percent_test.dart), used here as
// an independent oracle — NOT generated by running this Go code.

func TestPercent_RoyalRoiLa(t *testing.T) {
	cases := []struct {
		value string
		want  string
	}{
		// integer
		{"25", "ร้อยละยี่สิบห้า"},
		{"100", "ร้อยละหนึ่งร้อย"},
		{"0", "ร้อยละศูนย์"},
		// decimal
		{"25.5", "ร้อยละยี่สิบห้าจุดห้า"},
		{"0.5", "ร้อยละศูนย์จุดห้า"},
		// whole double reads as integer
		{"25.0", "ร้อยละยี่สิบห้า"},
		// negative
		{"-5", "ร้อยละลบห้า"},
	}
	for _, c := range cases {
		got, err := Percent(c.value, RoyalRoiLa)
		if err != nil {
			t.Fatalf("Percent(%q, RoyalRoiLa) unexpected error: %v", c.value, err)
		}
		if got != c.want {
			t.Errorf("Percent(%q, RoyalRoiLa) = %q, want %q", c.value, got, c.want)
		}
	}
}

func TestPercent_ColloquialPercent(t *testing.T) {
	cases := []struct {
		value string
		want  string
	}{
		{"25", "ยี่สิบห้าเปอร์เซ็นต์"},
		{"25.5", "ยี่สิบห้าจุดห้าเปอร์เซ็นต์"},
	}
	for _, c := range cases {
		got, err := Percent(c.value, ColloquialPercent)
		if err != nil {
			t.Fatalf("Percent(%q, ColloquialPercent) unexpected error: %v", c.value, err)
		}
		if got != c.want {
			t.Errorf("Percent(%q, ColloquialPercent) = %q, want %q", c.value, got, c.want)
		}
	}
}

func TestPercent_DefaultStyleIsRoyalRoiLa(t *testing.T) {
	// RoyalRoiLa is the zero value, so it must be the default style.
	if RoyalRoiLa != 0 {
		t.Fatalf("RoyalRoiLa = %d, want 0 (zero value / default)", RoyalRoiLa)
	}
}

func TestPercent_Invalid(t *testing.T) {
	for _, bad := range []string{"", "abc", "2.5.5", "%", "--5"} {
		if _, err := Percent(bad, RoyalRoiLa); err == nil {
			t.Errorf("Percent(%q, RoyalRoiLa) expected error, got nil", bad)
		}
	}
}

func TestPercentInt(t *testing.T) {
	cases := []struct {
		value int64
		style PercentStyle
		want  string
	}{
		{25, RoyalRoiLa, "ร้อยละยี่สิบห้า"},
		{100, RoyalRoiLa, "ร้อยละหนึ่งร้อย"},
		{0, RoyalRoiLa, "ร้อยละศูนย์"},
		{-5, RoyalRoiLa, "ร้อยละลบห้า"},
		{25, ColloquialPercent, "ยี่สิบห้าเปอร์เซ็นต์"},
	}
	for _, c := range cases {
		if got := PercentInt(c.value, c.style); got != c.want {
			t.Errorf("PercentInt(%d, %d) = %q, want %q", c.value, c.style, got, c.want)
		}
	}
}

func TestFormatPercent(t *testing.T) {
	cases := []struct {
		value string
		want  string
	}{
		// integer
		{"25", "25%"},
		{"0", "0%"},
		// fractional trims trailing zeros
		{"25.5", "25.5%"},
		{"25.0", "25%"},
		{"25.50", "25.5%"},
		// extra coverage
		{"0.5", "0.5%"},
		{"-5", "-5%"},
		{"100", "100%"},
	}
	for _, c := range cases {
		got, err := FormatPercent(c.value)
		if err != nil {
			t.Fatalf("FormatPercent(%q) unexpected error: %v", c.value, err)
		}
		if got != c.want {
			t.Errorf("FormatPercent(%q) = %q, want %q", c.value, got, c.want)
		}
	}
}

func TestFormatPercent_Invalid(t *testing.T) {
	for _, bad := range []string{"", "abc", "2.5.5", "%"} {
		if _, err := FormatPercent(bad); err == nil {
			t.Errorf("FormatPercent(%q) expected error, got nil", bad)
		}
	}
}
